name = "entomologist"
version = "0.0.0"

description = "ğŸ”ğŸ› In-database error tracking and reporting in gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "DisguisedPigeon", repo = "entomologist" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
pog = ">= 3.2.0 and < 4.0.0"
exception = ">= 2.0.0 and < 3.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 3.0.3 and < 4.0.0"
