name = "entomologist"
version = "0.0.0"

description = "ğŸ”ğŸ› In-database error tracking and reporting in gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "DisguisedPigeon", repo = "entomologist" }
links = [{ title = "Entomologist extensions", href = "https://www.github.com/DisguisedPigeon/entomologist-extensions" }]

target = "erlang"

[dependencies]
pog = ">= 4.1.0 and < 5.0.0"
exception = ">= 2.1.0 and < 3.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
squirrel = ">= 4.5.0 and < 5.0.0"
birdie = ">= 1.4.1 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
qcheck_gleeunit_utils = ">= 1.0.0 and < 2.0.0"
