name = "entomologist"
version = "0.0.0"

description = "ğŸ”ğŸ› In-database error tracking and reporting in gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "DisguisedPigeon", repo = "entomologist" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
